namespace :setup do
  current_link = 'tmp/hadoop-current'

  task :hadoop do
    hadoop_release = ENV['HADOOP_RELEASE'] || 'hadoop-2.2.0/hadoop-2.2.0'
    hadoop_url = "http://archive.apache.org/dist/hadoop/common/#{hadoop_release}.tar.gz"
    target_dir = "tmp/#{File.dirname(hadoop_release)}"
    FileUtils.mkdir_p(target_dir)
    Dir.chdir(target_dir) do
      unless File.exists?("#{File.basename(hadoop_release)}.tar.gz")
        command = (<<-END).lines.map(&:strip).join(' && ')
        curl --progress-bar -O '#{hadoop_url}'
        tar xf hadoop*.tar.gz
        END
        system(command)
      end
    end
    FileUtils.rm_f(current_link)
    FileUtils.ln_sf(Dir["#{target_dir}/hadoop*"].sort.first[4..-1], current_link)
  end

  task :classpath do
    File.open('.classpath', 'w') do |io|
      %x(#{current_link}/bin/hadoop classpath).chomp.split(':').each do |pattern|
        Dir[pattern].each do |path|
          io.puts(path)
        end
      end
    end
  end
end

task :setup => ['setup:hadoop', 'setup:classpath']
